apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-console-access
  labels:
    control-plane: vm-console-access
    name: vm-console-access
spec:
  selector:
    matchLabels:
      control-plane: vm-console-access
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: vm-console-access
        name: vm-console-access
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - command:
            - /console
          imagePullPolicy: Always
          args: []
          image: quay.io/akrejcir/vm-console-access:latest
          name: console
          ports:
            - name: api
              protocol: TCP
              containerPort: 8768
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
      terminationGracePeriodSeconds: 10
