apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-console-access
  labels:
    control-plane: vm-console-access
    name: vm-console-access
spec:
  selector:
    matchLabels:
      control-plane: vm-console-access
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: vm-console-access
        name: vm-console-access
    spec:
      serviceAccountName: vm-console-access
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - command:
            - /console
          args: []
          image: vm-console-access:latest
          name: console
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
          ports:
            - name: api
              protocol: TCP
              containerPort: 8443
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      terminationGracePeriodSeconds: 10
