apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - route.yaml
  - service.yaml

images:
  - name: console
    newName: quay.io/akrejcir/vm-console-proxy
    newTag: latest
