apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubevirt

resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
  - service_account.yaml
  - role.yaml
  - role_binding.yaml

images:
  - name: console
    newName: quay.io/akrejcir/vm-console-proxy
    newTag: latest
